### ISSUE TITLE
Will not work in Serverless v3

### ISSUE THREAD

**Issue by shengslogar** [tho-asterist/serverless-whitelisting#1]
https://github.com/tho-asterist/serverless-whitelisting/blob/f1ebd2d2fb92a2ec080834059dfe7dc1e970b893/index.js#L100

[`resourcePolicy` has been moved under the `apiGateway` block as of v3.](https://www.serverless.com/framework/docs/deprecations#api-gateway-specific-configuration)

Can make a PR if there's interest. Figured this was worth flagging.

**Comment by tho-asterist** [comment]
@shengslogar Thank you for your figure out. Please make the pull request.

**Comment by shengslogar** [comment]
Sorry, no longer have bandwidth to get to this. Hopefully someone else can.

**Comment by cjuega** [comment]
This issue is not fixed in the PR above.

Can you please release a new version whenever you feel it can be merged?
